stages:
  - README_SYNC

sync_readme:
  stage: README_SYNC
  image: alpine:latest
  variables:
    TEMPLATE_FILE: "README.tpl.md"
    OUTPUT_FILE: "README.md"
  before_script:
    - apk add --no-cache curl ca-certificates git openssh bash

    - curl -LsSf https://astral.sh/uv/install.sh | env UV_UNMANAGED_INSTALL="/usr/local/bin" sh
    
    - git config --global user.email "ci-bot@example.com"
    - git config --global user.name "README Sync Bot"
    - git config --global --add safe.directory $CI_PROJECT_DIR
  script:
    - |
      for tpl_file in $(find . -name "*.tpl.md"); do

        out_file="${tpl_file%.tpl.md}.md"
        echo "⚙️ Przetwarzanie: $tpl_file -> $out_file"
        uv run jinja2 -I ./ "$tpl_file" > "$out_file"
        
        git add "$out_file"
      done
    
    - |
      if [ -n "$(git status --porcelain)" ]; then
        echo "Wykryto zmiany w plikach .md, aktualizuję repozytorium..."
        git commit -m "docs: Automatic sync [skip ci]"
        
        git push -o ci.skip "https://project_${CI_PROJECT_ID}_bot:${ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" HEAD:${CI_COMMIT_REF_NAME}
      else
        echo "Wszystkie dokumenty są aktualne. Brak zmian."
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - "**/*.tpl.md"
        - "**/*.md"
        - "**/*.g4"
        - "examples/*"
        - "**/*.yml"
        - "**/*.nope"