stages:
  - SYNC

.sys_image:
  image: alpine:latest
  before_script:
    # - apk add --no-cache curl ca-certificates git openssh bash graphviz ttf-freefont
    - apk add --no-cache curl ca-certificates git openssh bash graphviz ttf-freefont openjdk17-jre ruff    
    - curl -LsSf https://astral.sh/uv/install.sh | env UV_UNMANAGED_INSTALL="/usr/local/bin" sh
    - git config --global user.email "ci-bot@example.com"
    - git config --global user.name "README Sync Bot"
    - git config --global --add safe.directory $CI_PROJECT_DIR
    
    - export $(grep -v '^#' .env | xargs)

sync_readme:
  extends: .sys_image
  stage: SYNC
  variables:
    TEMPLATE_FILE: "README.tpl.md"
    OUTPUT_FILE: "README.md"
  script:
    - |
      for tpl_file in $(find . -name "*.tpl.md"); do

        out_file="${tpl_file%.tpl.md}.md"
        echo "⚙️ Przetwarzanie: $tpl_file -> $out_file"
        uv run jinja2 -I ./ "$tpl_file" > "$out_file"
        
        git add "$out_file"
      done

    - uv run antlr4 -Dlanguage=Python3 -visitor -o src/nope/antlr_generated NOPE.g4
    - ruff format ./
    - git add src/*

    - uv build

    - rm graphs/*
    - uv run nope examples/in/*.nope -co examples/out -go graphs --generate-graph
    - find graphs/ -type f ! -name "*.png" -delete
    - git add -A graphs/
    
    - |
      if [ -n "$(git status --porcelain)" ]; then
        echo "Wykryto zmiany w plikach aktualizuję repozytorium..."
        git commit -m "Automatic docs + grammar sync"
        
        git push -o ci.skip "https://project_${CI_PROJECT_ID}_bot:${ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" HEAD:${CI_COMMIT_REF_NAME}
      else
        echo "Wszystkie pliki są aktualne. Brak zmian."
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - "**/*.tpl.md"
        - "**/*.md"
        - "**/*.g4"
        - "examples/*"
        - "**/*.yml"
        - "**/*.nope"
        - "graphs/*"
        - "src/nope/GraphRenderer.py"
        - "src/nope/nope_runtime.h"
        - "src/nope/nope_runtime.c"
        - "src/nope/NOPECompiler.py"
        - "src/nope/NOPELinter.py"
        - "src/nope/main.py"
        - ".gitlab-ci.yml"
