import sys
from typing import Optional
from antlr4 import *
from antlr4.tree.Tree import ParseTree, TerminalNode
from pathlib import Path
import graphviz
from src.NOPEParser import NOPEParser
from src.NOPELexer import NOPELexer


class GraphRenderer:
    """Class responsible for rendering the ANTLR parse tree to Graphviz format."""

    def __init__(self, parser: Parser, graph: graphviz.graphs.BaseGraph) -> None:
        """
        Initializes the renderer.
        It is recommended to use factory methods (e.g., create_styled_digraph)
        instead of direct instantiation.
        """
        self.parser: Parser = parser
        self.graph: graphviz.graphs.BaseGraph = graph
        self._counter: int = 0

    @classmethod
    def create_default_digraph(
        cls, parser: Parser, comment: str = "ANTLR Parse Tree"
    ) -> "GraphRenderer":
        """Factory method creating a standard, pure-white directed graph."""
        dot = graphviz.Digraph(comment=comment)
        return cls(parser, dot)

    @classmethod
    def create_styled_digraph(
        cls, parser: Parser, comment: str = "ANTLR Parse Tree"
    ) -> "GraphRenderer":
        """Factory method creating a styled graph (rounded corners, colors, font)."""
        dot = graphviz.Digraph(comment=comment)
        dot.attr(
            "node",
            shape="box",
            style="rounded,filled",
            color="lightblue",
            fontname="Helvetica",
        )
        return cls(parser, dot)

    def _build_nodes(self, tree: ParseTree, parent_id: Optional[str] = None) -> str:
        token_name = None
        
        if isinstance(tree, TerminalNode):
            symbol = tree.getSymbol()
            
            if symbol.type == Token.EOF:
                token_name = "EOF"
                text = ""
            else:
                token_name = self.parser.symbolicNames[symbol.type]
                text = tree.getText()
                
                if not token_name or token_name == "<INVALID>":
                    token_name = "TOKEN"

            if token_name == "EOF":
                label = "EOF"
            else:
                label = f"{token_name}\n'{text}'"
        else:
            rule_index = tree.getRuleIndex()
            label = self.parser.ruleNames[rule_index]

        safe_label = label.replace("\\", "\\\\").replace('"', '\\"')
        safe_label = safe_label.replace("\n", "\\n").replace("\r", "")

        node_id = str(self._counter)
        self._counter += 1


        if isinstance(tree, TerminalNode):
            if token_name in ["SPACE", "ENDL"]:
                self.graph.node(
                    node_id, 
                    safe_label, 
                    shape="ellipse", 
                    # style="filled", 
                    color="lightgray", 
                    fontcolor="gray"
                )
            else:
                self.graph.node(
                    node_id, 
                    safe_label, 
                    shape="box", 
                    style="filled", 
                    color="lightgreen",
                    fontcolor="black"
                )
        else:

            if label == "ws":
                self.graph.node(
                    node_id, 
                    safe_label, 
                    color="gainsboro",
                    fontcolor="gray"
                )
            else:
                self.graph.node(
                    node_id, 
                    safe_label,
                    fontcolor="black"
                )

        if parent_id is not None:
            if (isinstance(tree, TerminalNode) and token_name in ["SPACE", "ENDL"]) or label == "ws":
                self.graph.edge(parent_id, node_id, color="lightgray")
            else:
                self.graph.edge(parent_id, node_id)

        if hasattr(tree, "children") and tree.children is not None:
            for child in tree.children:
                self._build_nodes(child, parent_id=node_id)

        return node_id

    def render(
        self,
        tree: ParseTree,
        filename: str = "tree",
        directory: Optional[Path] = None,
        file_format: str = "png",
        view: bool = True,
    ) -> None:
        """
        Builds the graph based on the parse tree and saves it to a file.

        :param tree: The parse tree generated by the ANTLR parser.
        :param filename: Output filename (without extension).
        :param directory: Output directory Path object where the file will be saved.
        :param file_format: File format (e.g., 'png', 'pdf', 'svg').
        :param view: Whether to automatically open the generated file.
        """
        self._counter = 0
        self._build_nodes(tree)
        out_dir = str(directory) if directory is not None else None

        try:
            self.graph.render(
                filename, directory=out_dir, format=file_format, view=view
            )
        except Exception as ex:
            print(f"Cannot render graph properly, Exeption: {ex}")
