import sys
from typing import Optional
from antlr4 import *
from antlr4.tree.Tree import ParseTree, TerminalNode
from pathlib import Path
import graphviz


class GraphRenderer:
    """Class responsible for rendering the ANTLR parse tree to Graphviz format."""

    def __init__(self, parser: Parser, graph: graphviz.graphs.BaseGraph) -> None:
        """
        Initializes the renderer.
        It is recommended to use factory methods (e.g., create_styled_digraph)
        instead of direct instantiation.
        """
        self.parser: Parser = parser
        self.graph: graphviz.graphs.BaseGraph = graph
        self._counter: int = 0

    @classmethod
    def create_default_digraph(
        cls, parser: Parser, comment: str = "ANTLR Parse Tree"
    ) -> "GraphRenderer":
        """Factory method creating a standard, pure-white directed graph."""
        dot = graphviz.Digraph(comment=comment)
        return cls(parser, dot)

    @classmethod
    def create_styled_digraph(
        cls, parser: Parser, comment: str = "ANTLR Parse Tree"
    ) -> "GraphRenderer":
        """Factory method creating a styled graph (rounded corners, colors, font)."""
        dot = graphviz.Digraph(comment=comment)
        dot.attr(
            "node",
            shape="box",
            style="rounded,filled",
            color="lightblue",
            fontname="Helvetica",
        )
        return cls(parser, dot)

    def _build_nodes(self, tree: ParseTree, parent_id: Optional[str] = None) -> str:
        """Internal recursive method traversing the ANTLR tree."""
        node_id = str(self._counter)
        self._counter += 1

        # Determine the label for the node
        if isinstance(tree, TerminalNode):
            label = tree.getText()
        else:
            rule_index = tree.getRuleIndex()
            label = self.parser.ruleNames[rule_index]

        self.graph.node(node_id, label)

        if parent_id is not None:
            self.graph.edge(parent_id, node_id)

        if hasattr(tree, "children") and tree.children is not None:
            for child in tree.children:
                self._build_nodes(child, parent_id=node_id)

        return node_id

    def render(
        self,
        tree: ParseTree,
        filename: str = "tree",
        directory: Optional[Path] = None,
        file_format: str = "png",
        view: bool = True,
    ) -> None:
        """
        Builds the graph based on the parse tree and saves it to a file.

        :param tree: The parse tree generated by the ANTLR parser.
        :param filename: Output filename (without extension).
        :param directory: Output directory Path object where the file will be saved.
        :param file_format: File format (e.g., 'png', 'pdf', 'svg').
        :param view: Whether to automatically open the generated file.
        """
        self._counter = 0
        self._build_nodes(tree)
        out_dir = str(directory) if directory is not None else None

        try:
            self.graph.render(
                filename, directory=out_dir, format=file_format, view=view
            )
        except Exception as ex:
            print(f"Cannot render graph properly, Exeption: {ex}")
